title: Monadotory
author:
  name: Vũ Tuấn Hải
  email: vutuanhai237@gmail.com
description: Resource notebook của tôi, nơi ghi lại những trăn trở trong đầu
show_excerpts: false 
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: https://github.com/vutuanhai237
    facebook: https://www.facebook.com/vutuanhai237
    instagram: https://www.instagram.com/vutuanhai237/
    linkedin: https://www.linkedin.com/in/vutuanhai237/
    youtube: /c/VũTuấnHải
theme: minima
ignore_theme_config: false
plugins:
 - jekyll-feed
 - jekyll-seo-tag
