title: Monadotory
author:
  name: Vũ Tuấn Hải
  email: vutuanhai237@gmail.com
description: Research notebook của tôi, nơi ghi lại những trăn trở trong đầu
show_excerpts: false 
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github: vutuanhai237
    facebook: vutuanhai237
    instagram: vutuanhai237
    linkedin: vutuanhai237
    youtube: VũTuấnHải
theme: minima
google_analytics: UA-NNNNNNNN-N
ignore_theme_config: false
plugins:
 - jekyll-feed
 - jekyll-seo-tag
